[package]
name = "aleo-std-profiler"
version = "0.1.10"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A profiler to measure runtime performance"
license = "GPL-3.0"
edition = "2018"

[dependencies.colored]
version = "2"
optional = true

[features]
profiler = [ "colored" ]
