[package]
name = "aleo-std-cpu"
version = "0.1.4"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Convenience method for retrieving CPU information"
license = "GPL-3.0"
edition = "2018"
