[package]
name = "aleo-std-timer"
version = "0.1.0"
authors = ["howardwu <howardwu@berkeley.edu>"]
license = "GPL-3.0"
edition = "2018"

[dependencies.colored]
version = "2"
optional = true

[features]
default = []
timer = ["colored"]
